import React from "react";
import { Carousel, CarouselContent, CarouselItem, CarouselNext, CarouselPrevious } from "./carousel";
import { Button } from "./button";

const categories = [
  "Frontend Developer",
  "Backend Developer",
  "Full-Stack Developer",
  "UI/UX Designer",
  "Web Developer",
  "Mobile App Developer",
  "Software Engineer",
  "Game Developer",
  "Data Scientist",
  "Machine Learning Engineer",
  "AI Specialist",
  "Cybersecurity Analyst",
  "Ethical Hacker",
  "Cloud Engineer",
  "DevOps Engineer",
  "Database Administrator",
  "Network Engineer",
  "System Administrator",
  "IT Support Specialist",
  "Technical Writer",
  "Product Manager",
  "Project Manager",
  "IT Consultant",
  "Solutions Architect",
  "Big Data Engineer",
  "Blockchain Developer",
  "Data Analyst",
  "Business Intelligence Analyst",
  "Enterprise Architect",
  "Site Reliability Engineer (SRE)",
  "IoT Developer",
  "Information Security Analyst",
  "Penetration Tester",
  "Cryptography Engineer",
  "Computer Vision Engineer",
  "Natural Language Processing (NLP) Engineer",
  "Augmented Reality (AR) Developer",
  "Virtual Reality (VR) Developer",
  "Mobile Game Developer",
  "Robotics Engineer",
  "Firmware Developer",
  "Embedded Systems Engineer",
  "Application Support Specialist",
  "Release Manager",
  "Technical Program Manager",
  "ERP Consultant",
  "SAP Developer",
  "CRM Specialist",
  "IT Auditor",
  "QA Engineer",
  "Test Automation Engineer",
  "Performance Test Engineer",
  "Load Test Specialist",
  "Security Test Engineer",
  "Configuration Manager",
  "IT Compliance Specialist",
  "Help Desk Technician",
  "IT Operations Manager",
  "Storage Administrator",
  "Backup and Recovery Specialist",
  "Software Architect",
  "API Developer",
  "Integration Engineer",
  "Middleware Developer",
  "Cloud Solutions Architect",
  "Kubernetes Specialist",
  "Docker Specialist",
  "AWS Cloud Specialist",
  "Azure Cloud Specialist",
  "Google Cloud Specialist",
  "OpenStack Developer",
  "Serverless Developer",
  "Distributed Systems Engineer",
  "Messaging Systems Engineer",
  "Streaming Data Engineer",
  "AI Ethics Specialist",
  "Data Governance Specialist",
  "IT Trainer",
  "Digital Transformation Specialist",
  "IT Asset Manager",
  "Technical Support Engineer",
  "Application Developer",
  "Middleware Administrator",
  "Platform Engineer",
  "Security Operations Center (SOC) Analyst",
  "Incident Response Specialist",
  "Risk Analyst",
  "IT Risk Manager",
  "Data Privacy Officer",
  "Chief Information Officer (CIO)",
  "Chief Technology Officer (CTO)",
  "Chief Information Security Officer (CISO)",
  "IT Service Delivery Manager",
  "Identity and Access Management (IAM) Specialist",
  "Desktop Support Technician",
  "Virtualization Engineer",
  "Power BI Developer",
  "Tableau Developer",
  "Data Warehouse Developer",
  "Hadoop Developer",
  "Spark Developer",
  "ETL Developer",
  "Cloud Migration Specialist",
  "Software Deployment Engineer",
  "Software Configuration Manager",
  "Version Control Specialist",
  "Linux System Administrator",
  "Windows System Administrator",
  "IT Automation Specialist",
  "IT Change Manager",
  "IT Incident Manager",
  "Middleware Support Engineer",
  "ServiceNow Developer",
  "Splunk Engineer",
  "Monitoring Engineer",
  "NoSQL Database Specialist",
  "SQL Database Specialist",
  "Graph Database Developer",
  "Web Security Specialist",
  "Information Systems Manager",
  "Health IT Specialist",
  "Education Technology Specialist",
  "Agile Coach",
  "Scrum Master",
  "Kanban Specialist",
  "IT Accessibility Specialist",
  "Mobile Security Analyst",
  "Data Backup Administrator",
  "IT Infrastructure Manager",
  "Digital Forensics Specialist",
  "AI Operations Engineer",
  "Data Engineering Specialist",
  "Cloud Native Developer",
  "Mobile Optimization Specialist",
  "IT Networking Specialist",
  "Containerization Expert",
  "Data Science Consultant",
  "IT Integration Specialist",
  "Data Visualization Specialist",
  "Cross-Platform App Developer",
  "Open Source Contributor",
  "Python Developer",
  "Java Developer",
  "C++ Developer",
  "C# Developer",
  "JavaScript Developer",
  "Ruby on Rails Developer",
  "PHP Developer",
  "Go Developer",
  "Rust Developer",
  "Kotlin Developer",
  "Swift Developer",
  "TypeScript Developer",
  "Perl Developer",
  "Shell Scripting Specialist",
];

const CategoryDisplay = () => {
  return (
    <div>
      <Carousel className="w-full max-w-xl mx-auto my-20">
        <CarouselContent>
          {categories.map((cat, index) => (
            <CarouselItem key={index} className="md:basis-1/3">
                <Button className="bg-orange-100 text-orange-600 w-max text-[12px]">{cat}</Button>
            </CarouselItem>
          ))}
        </CarouselContent>
        <CarouselPrevious />
        <CarouselNext />
      </Carousel>
    </div>
  );
};

export default CategoryDisplay;
